<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Casts\Attribute;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Category extends Model
{
    use HasFactory;
    protected $primaryKey = 'id';

 protected $guarded=[];

    public function posts(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(Post::class);
    }
    public function getRouteKeyName(): string
    {
        return 'slug'; // TODO: Change the autogenerated stub
    }

    protected function slug():Attribute
    {
        return Attribute::make(
            get: fn(string $slug)=> ucwords($slug),
        );
    }
    protected function title():Attribute
    {
        return Attribute::make(
            get: fn(string $title)=> ucwords($title),
        );
    }

}
